### ISSUE TITLE
A queue already exists with the same name and a different value for attribute RedrivePolicy

### ISSUE THREAD

**Issue by dariusdamalakas** [justeat/JustSaying#208]
I am not yet sure as to the origins of the error, potentially JustSaying is trying to create the queue twice, but I have not looked what is the root cause.

```
 justSaying
                .WithSqsTopicSubscriber()
                    .IntoQueue("queue1")
                        .ConfigureSubscriptionWith(x =>
                        {
                            x.VisibilityTimeoutSeconds = (int)TimeSpan.FromHours(12).TotalSeconds;
                            x.RetryCountBeforeSendingToErrorQueue = 1;
                        })
                .WithMessageHandler<Handler1>(handlerResolver)
                .WithSqsPointToPointSubscriber()
                    .IntoQueue("queue1")
                    .ConfigureSubscriptionWith(x =>
                    {
                        x.VisibilityTimeoutSeconds = (int)TimeSpan.FromHours(12).TotalSeconds;
                        x.RetryCountBeforeSendingToErrorQueue = 1;
                    })
                .WithMessageHandler<Handler2>(handlerResolver)
```

The above code fails with this error. I have not found a workaround for this, except for removing sqs point to point subscriber and switching to sns subscriber

```
2016-06-07 09:19:24,191 [7] INFO  JustSaying [(null)] - Created Queue: dev-dariouso-ringcentral2_error on Arn: arn:aws:sqs:eu-west-1:xxxxxx:dev-dariouso-ringcentral2_error
2016-06-07 09:19:24,268 [7] ERROR JustSaying [(null)] - Create Queue error: dev-dariouso-ringcentral2
Amazon.SQS.Model.QueueNameExistsException: A queue already exists with the same name and a different value for attribute RedrivePolicy ---> Amazon.Runtime.Internal.HttpErrorResponseException: The remote server returned an error: (400) Bad Request. ---> System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at System.Net.HttpWebRequest.GetResponse()
   at Amazon.Runtime.Internal.HttpRequest.GetResponse() in d:\Jenkins\jobs\build-sdkandtools-release\workspace\sdk\src\AWSSDK_DotNet35\Amazon.Runtime\Pipeline\HttpHandler\HttpWebRequestFactory.cs:line 106
   --- End of inner exception stack trace ---
   at Amazon.Runtime.Internal.HttpRequest.GetResponse() in d:\Jenkins\jobs\build-sdkandtools-release\workspace\sdk\src\AWSSDK_DotNet35\Amazon.Runtime\Pipeline\HttpHandler\HttpWebRequestFactory.cs:line 114
   at Amazon.Runtime.Internal.HttpHandler`1.InvokeSync(IExecutionContext executionContext) in d:\Jenkins\jobs\build-sdkandtools-release\workspace\sdk\src\AWSSDK_DotNet35\Amazon.Runtime\Pipeline\HttpHandler\HttpHandler.cs:line 84
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in d:\Jenkins\jobs\build-sdkandtools-release\workspace\sdk\src\AWSSDK_DotNet35\Amazon.Runtime\Pipeline\PipelineHandler.cs:line 55
   at Amazon.Runtime.Internal.Unmarshaller.InvokeSync(IExecutionContext executionContext) in d:\Jenkins\jobs\build-sdkandtools-release\workspace\sdk\src\AWSSDK_DotNet35\Amazon.Runtime\Pipeline\Handlers\Unmarshaller.cs:line 47
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in d:\Jenkins\jobs\build-sdkandtools-release\workspace\sdk\src\AWSSDK_DotNet35\Amazon.Runtime\Pipeline\PipelineHandler.cs:line 55
   at Amazon.SQS.Internal.ValidationResponseHandler.InvokeSync(IExecutionContext executionContext) in d:\Jenkins\jobs\build-sdkandtools-release\workspace\sdk\src\AWSSDK_DotNet35\Amazon.SQS\Internal\ValidationResponseHandler.cs:line 25
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in d:\Jenkins\jobs\build-sdkandtools-release\workspace\sdk\src\AWSSDK_DotNet35\Amazon.Runtime\Pipeline\PipelineHandler.cs:line 55
   at Amazon.Runtime.Internal.ErrorHandler.InvokeSync(IExecutionContext executionContext) in d:\Jenkins\jobs\build-sdkandtools-release\workspace\sdk\src\AWSSDK_DotNet35\Amazon.Runtime\Pipeline\ErrorHandler\ErrorHandler.cs:line 70
   --- End of inner exception stack trace ---
   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleException(IExecutionContext executionContext, HttpErrorResponseException exception) in d:\Jenkins\jobs\build-sdkandtools-release\workspace\sdk\src\AWSSDK_DotNet35\Amazon.Runtime\Pipeline\ErrorHandler\HttpErrorResponseExceptionHandler.cs:line 99
   at Amazon.Runtime.Internal.ExceptionHandler`1.Handle(IExecutionContext executionContext, Exception exception) in d:\Jenkins\jobs\build-sdkandtools-release\workspace\sdk\src\AWSSDK_DotNet35\Amazon.Runtime\Pipeline\ErrorHandler\ExceptionHandler.cs:line 38
   at Amazon.Runtime.Internal.ErrorHandler.ProcessException(IExecutionContext executionContext, Exception exception) in d:\Jenkins\jobs\build-sdkandtools-release\workspace\sdk\src\AWSSDK_DotNet35\Amazon.Runtime\Pipeline\ErrorHandler\ErrorHandler.cs:line 202
   at Amazon.Runtime.Internal.ErrorHandler.InvokeSync(IExecutionContext executionContext) in d:\Jenkins\jobs\build-sdkandtools-release\workspace\sdk\src\AWSSDK_DotNet35\Amazon.Runtime\Pipeline\ErrorHandler\ErrorHandler.cs:line 76
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in d:\Jenkins\jobs\build-sdkandtools-release\workspace\sdk\src\AWSSDK_DotNet35\Amazon.Runtime\Pipeline\PipelineHandler.cs:line 55
   at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext) in d:\Jenkins\jobs\build-sdkandtools-release\workspace\sdk\src\AWSSDK_DotNet35\Amazon.Runtime\Pipeline\Handlers\CallbackHandler.cs:line 45
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in d:\Jenkins\jobs\build-sdkandtools-release\workspace\sdk\src\AWSSDK_DotNet35\Amazon.Runtime\Pipeline\PipelineHandler.cs:line 55
   at Amazon.Runtime.Internal.Signer.InvokeSync(IExecutionContext executionContext) in d:\Jenkins\jobs\build-sdkandtools-release\workspace\sdk\src\AWSSDK_DotNet35\Amazon.Runtime\Pipeline\Handlers\Signer.cs:line 38
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in d:\Jenkins\jobs\build-sdkandtools-release\workspace\sdk\src\AWSSDK_DotNet35\Amazon.Runtime\Pipeline\PipelineHandler.cs:line 55
   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeSync(IExecutionContext executionContext) in d:\Jenkins\jobs\build-sdkandtools-release\workspace\sdk\src\AWSSDK_DotNet35\Amazon.Runtime\Pipeline\Handlers\CredentialsRetriever.cs:line 72
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in d:\Jenkins\jobs\build-sdkandtools-release\workspace\sdk\src\AWSSDK_DotNet35\Amazon.Runtime\Pipeline\PipelineHandler.cs:line 55
   at Amazon.Runtime.Internal.RetryHandler.InvokeSync(IExecutionContext executionContext) in d:\Jenkins\jobs\build-sdkandtools-release\workspace\sdk\src\AWSSDK_DotNet35\Amazon.Runtime\Pipeline\RetryHandler\RetryHandler.cs:line 84
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in d:\Jenkins\jobs\build-sdkandtools-release\workspace\sdk\src\AWSSDK_DotNet35\Amazon.Runtime\Pipeline\PipelineHandler.cs:line 55
   at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext) in d:\Jenkins\jobs\build-sdkandtools-release\workspace\sdk\src\AWSSDK_DotNet35\Amazon.Runtime\Pipeline\Handlers\CallbackHandler.cs:line 45
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in d:\Jenkins\jobs\build-sdkandtools-release\workspace\sdk\src\AWSSDK_DotNet35\Amazon.Runtime\Pipeline\PipelineHandler.cs:line 55
   at Amazon.Runtime.Internal.EndpointResolver.InvokeSync(IExecutionContext executionContext) in d:\Jenkins\jobs\build-sdkandtools-release\workspace\sdk\src\AWSSDK_DotNet35\Amazon.Runtime\Pipeline\Handlers\EndpointResolver.cs:line 34
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in d:\Jenkins\jobs\build-sdkandtools-release\workspace\sdk\src\AWSSDK_DotNet35\Amazon.Runtime\Pipeline\PipelineHandler.cs:line 55
   at Amazon.SQS.Internal.ProcessRequestHandler.InvokeSync(IExecutionContext executionContext) in d:\Jenkins\jobs\build-sdkandtools-release\workspace\sdk\src\AWSSDK_DotNet35\Amazon.SQS\Internal\ProcessRequestHandler.cs:line 23
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in d:\Jenkins\jobs\build-sdkandtools-release\workspace\sdk\src\AWSSDK_DotNet35\Amazon.Runtime\Pipeline\PipelineHandler.cs:line 55
   at Amazon.Runtime.Internal.Marshaller.InvokeSync(IExecutionContext executionContext) in d:\Jenkins\jobs\build-sdkandtools-release\workspace\sdk\src\AWSSDK_DotNet35\Amazon.Runtime\Pipeline\Handlers\Marshaller.cs:line 37
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in d:\Jenkins\jobs\build-sdkandtools-release\workspace\sdk\src\AWSSDK_DotNet35\Amazon.Runtime\Pipeline\PipelineHandler.cs:line 55
   at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext) in d:\Jenkins\jobs\build-sdkandtools-release\workspace\sdk\src\AWSSDK_DotNet35\Amazon.Runtime\Pipeline\Handlers\CallbackHandler.cs:line 45
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in d:\Jenkins\jobs\build-sdkandtools-release\workspace\sdk\src\AWSSDK_DotNet35\Amazon.Runtime\Pipeline\PipelineHandler.cs:line 55
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeSync(IExecutionContext executionContext) in d:\Jenkins\jobs\build-sdkandtools-release\workspace\sdk\src\AWSSDK_DotNet35\Amazon.Runtime\Pipeline\Handlers\ErrorCallbackHandler.cs:line 44
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in d:\Jenkins\jobs\build-sdkandtools-release\workspace\sdk\src\AWSSDK_DotNet35\Amazon.Runtime\Pipeline\PipelineHandler.cs:line 55
   at Amazon.Runtime.Internal.MetricsHandler.InvokeSync(IExecutionContext executionContext) in d:\Jenkins\jobs\build-sdkandtools-release\workspace\sdk\src\AWSSDK_DotNet35\Amazon.Runtime\Pipeline\Handlers\MetricsHandler.cs:line 40
   at Amazon.Runtime.Internal.RuntimePipeline.InvokeSync(IExecutionContext executionContext) in d:\Jenkins\jobs\build-sdkandtools-release\workspace\sdk\src\AWSSDK_DotNet35\Amazon.Runtime\Pipeline\RuntimePipeline.cs:line 135
   at Amazon.Runtime.AmazonServiceClient.Invoke[TRequest,TResponse](TRequest request, IMarshaller`2 marshaller, ResponseUnmarshaller unmarshaller) in d:\Jenkins\jobs\build-sdkandtools-release\workspace\sdk\src\AWSSDK_DotNet35\Amazon.Runtime\AmazonServiceClient.cs:line 117
   at Amazon.SQS.AmazonSQSClient.CreateQueue(CreateQueueRequest request) in d:\Jenkins\jobs\build-sdkandtools-release\workspace\sdk\src\AWSSDK_DotNet45\Amazon.SQS\AmazonSQSClient.cs:line 730
   at JustSaying.AwsTools.SqsQueueByNameBase.Create(SqsBasicConfiguration queueConfig, Int32 attempt)


```

**Comment by payman81** [comment]
I have never used both TopicSubscriber and PointToPoint subscriber into a queue. 
Did you intentionally name your queue 'queue1' for both subscribers? 
If yes then I don't understand your intentions. Do you want a topic based pub/sub or do you want to directly drop a message in a queue without a topic?

**Comment by dariusdamalakas** [comment]
@payman81 yes, both queue names are same.    And it works fine without the custom redrive policy. 

> Do you want a topic based pub/sub or do you want to directly drop a message in a queue without a topic?

It depends. My service might listen for `UserCreated` event (SNS subsription), and it might also listen for command `SendWelcomeEmail` message. Not ideal example, as it does not make much business sense what i've described here.

Both messages are send to same queue. Commands - directly to queue. Events - subscribes a queue to a topic. There is really no difference if queue is same in both cases.

**Comment by Singh400** [comment]
I have run into this problem with the plain AWS SDK. It is because for some reason AWS differs between:

1. Creating a queue and setting it's attributes at the same time, by using this [AmazonSQSClient.CreateQueue(CreateQueueRequest)](http://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/SQS/MSQSSQSCreateQueueCreateQueueRequest.html) blows up and you get the exception.
2. But creating a queue using [AmazonSQSClient.CreateQueue(string)](http://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/SQS/MSQSSQSCreateQueueString.html) and then setting the queue attributes with [AmazonSQSClient.SetQueueAttributes(string, Dictionary<string, string>)](http://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/SQS/MSQSSQSSetQueueAttributesStringDictionary!String,%20String!.html). I suspect because the latter overwrites.

**Comment by andrewchaa** [comment]
Hi Singh400, 
Thanks for the input. 

I've submitted a PR for the fix. 
https://github.com/justeat/JustSaying/pull/331

**Comment by tomhaigh** [comment]
Looks like this could be the cause of the problem: https://github.com/justeat/JustSaying/commit/9a9be6b413613223a5be312e32db0b0e4ac00996#diff-510a036709714161cb690792aba4801b
A change was made which means when determining if a queue exists, it switched from enumerating all queues to fetching the url of queues one-by-one. And our components that had problems with this versions only have permission to sqs:ListQueues and not sqs:GetQueueUrl. 
When you do not have permission it appears that `QueueDoesNotExistException` is thrown by the AWSSDK - so JustSaying would treat it as not existing and attempt queue creation.

So maybe the fixes in the recent PRs are sidestepping the issue somewhat- because in this situation where a queue already exists,` Create()` shouldn't ever be called in the first place, and making it work in this case shouldn't be necessary.

**Comment by andrewchaa** [comment]
@tomhaigh Thanks for figuring out the root cause. I suspected Exists() as this issue started happening quite of a sudden. Still, IMO, it's good to override the attribute to avoid any issues in the future.
